### ISSUE TITLE
implement lifetimes, remove tons of unnecessary heap allocated strings

### ISSUE THREAD

**Issue by PThorpe92** [PThorpe92/CuTE#104]
**Lots** of naive, useless heap allocations left over. As my first decent sized Rust project, there was quite a bit of learning going on. But now, going back and adding lifetimes and borrowing properly and not doing stupid clones everywhere, is necessary :+1: 

Starting to work on this, and the error poor error handling.

**Comment by KMastroluca** [comment]
work fast and break things brodie.

**Comment by PThorpe92** [comment]
>work fast and break things brodie

Changing 5 or 6 struct fields to borrowed str slices caused me to have to add approximately 799,999,472 lifetimes throughout the code base and counting :skull: 

However I'll admit it is pretty cringe looking at how much useless cloning there is going on everywhere..

**Comment by KMastroluca** [comment]
Share the memory. I'm not gonna lie to you, my understanding of pointers i feel like is finally come full circle. Memory is just an array of bytes no matter which way you look at it. As far as lifetimes go. I get the block scoping part of lifetimes, but I still don't think ive even encountered the more complicated version of lifetimes everyone keeps talking about.

**Comment by PThorpe92** [comment]
Rust tricks you at several points into thinking u have learned it. Then at several other points u realize that u just learned the syntax.

at first i didn't realize that you literally have to _constantly_ think about and remember
1. Where your data lives in memory
2. What owns the data you are dealing with at the time, and passing around ownership/references / "borrowing"
3. When using those references, you have to specify to the compiler how long those pointers will be valid for (with lifetimes)

for a while it's just shutting up the rustanalyzer, but after a while it finally makes sense and then you pay more attention to these things.
